ESW02-G02/ProjectSW/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;

namespace ProjectSW.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        /// <summary>Ação que resulta na lista de utilizadores</summary>
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Employee.Include(e => e.Account);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Employees/Details/5
        /// <summary>Ação que resulta numa pagina com os detalhes de uma utilizadores</summary>
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employee
                .Include(e => e.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        [Authorize(Roles = "Administrador, Funcionario")]
        /// <summary>Ação que resulta numa pagina com o formulario da criação de uma utilizadores</summary>
        public IActionResult Create()
        {
            ViewData["AccountId"] = new SelectList(_context.User, "Id", "Email");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta na criação de uma utilizadores</summary>
        public async Task<IActionResult> Create([Bind("Id,AccountId,Type,AditionalInformation")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.User, "Id", "Id", employee.AccountId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        [Authorize(Roles = "Administrador, Funcionario")]
        /// <summary>Ação que resulta numa pagina com os detalhes de um utilizador de forma a poderem ser editados</summary>
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employee.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["AccountId"] = new SelectList(_context.User, "Id", "Email", employee.AccountId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta numa pagina com a edição de uma utilizador</summary>
        public async Task<IActionResult> Edit(string id, [Bind("Id,AccountId,Type,AditionalInformation")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.User, "Id", "Id", employee.AccountId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        [Authorize(Roles = "Administrador")]
        /// <summary>Ação que resulta num prompt para apagar uma utilizador</summary>
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employee
                .Include(e => e.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta num utilizador apagada</summary>
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.Employee.FindAsync(id);
            _context.Employee.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(string id)
        {
            return _context.Employee.Any(e => e.Id == id);
        }
    }
}

ESW02-G02/ProjectSW/Controllers/JobsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace ProjectSW.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ProjectSWUser> _userManager;

        public JobsController(ApplicationDbContext context, UserManager<ProjectSWUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Jobs
        /// <summary>Ação que resulta na lista de Tarefas</summary>
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Job.Include(j => j.Employee).Include(j => j.Employee.Account);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Jobs/Details/5
        /// <summary>Ação que resulta numa pagina com os detalhes de uma tarefa</summary>
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.Employee).Include(j => j.Employee.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        [Authorize(Roles = "Administrador, Funcionario")]
        /// <summary>Ação que resulta numa pagina com o formulario da criação de uma tarefa</summary>
        public IActionResult Create()
        {
            //ViewData["EmployeeId"] = new SelectList(_context.Employee.Include(j => j.Account), "Account.Email", "Account.Email");
            ViewData["EmployeeId"] = new SelectList(_context.Employee.Join(
                   _context.User,
                   employee => employee.AccountId,
                   account => account.Id,
                      (employee, account) => new  // result selector
                      {
                          employeeId = employee.Id,
                          accountMail = account.Email
                      }), "employeeId", "accountMail");

            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta na criação de uma tarefa</summary>
        public async Task<IActionResult> Create([Bind("Id,EmployeeId,Name,Day,Hour,Description")] Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();

                var employee = await _userManager.FindByIdAsync(_context.Employee.Where(e => e.Id.Equals(job.EmployeeId)).FirstOrDefault().AccountId);

                var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
                //Antes de fazer push remover chave
                var client = new SendGridClient(apiKey);
                var msg = new SendGridMessage()
                {
                    From = new EmailAddress("QuintaDoMiao@exemplo.com", "Quinta do Miao"),
                    PlainTextContent = "Nova tarefa",
                    Subject = "Nova tarefa",
                    HtmlContent = $"Olá.<br><br>Foi-lhe atribuido uma nova tarefa a completar, por favor verifique a lista de tarefas.<br><br>" +
                    "Cumprimentos,<br>Quinta do Mião."
                };
                msg.AddTo(new EmailAddress(employee.Email, employee.Name));
                var response = await client.SendEmailAsync(msg);
         
                return RedirectToAction(nameof(Index));
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employee.Join(
                _context.User,
                employee => employee.AccountId,
                account => account.Id,
                (employee, account) => new  // result selector
                {
                    employeeId = employee.Id,
                    accountMail = account.Email
                }), "employeeId", "accountMail");

            return View(job);
        }


        // GET: Jobs/Edit/5
        [Authorize(Roles = "Administrador, Funcionario")]
        /// <summary>Ação que resulta numa pagina com os detalhes de uma tarefa de forma a poderem ser editados</summary>
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employee.Join(
                   _context.User,
                   employee => employee.AccountId,
                   account => account.Id,
                      (employee, account) => new  // result selector
                      {
                          employeeId = employee.Id,
                          accountMail = account.Email
                      }), "employeeId", "accountMail");
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta numa pagina com a edição de uma tarefa</summary>
        public async Task<IActionResult> Edit(string id, [Bind("Id,EmployeeId,Name,Day,Hour,Description")] Job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employee.Join(
                   _context.User,
                   employee => employee.AccountId,
                   account => account.Id,
                      (employee, account) => new  // result selector
                      {
                          employeeId = employee.Id,
                          accountMail = account.Email
                      }), "employeeId", "accountMail");
            return View(job);
        }

        // GET: Jobs/Delete/5
        [Authorize(Roles = "Administrador")]
        /// <summary>Ação que resulta num prompt para apagar uma tarefa</summary>
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.Employee.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta numa tarefa apagada</summary>
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var job = await _context.Job.FindAsync(id);
            _context.Job.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(string id)
        {
            return _context.Job.Any(e => e.Id == id);
        }
    }
}

ESW02-G02/ProjectSW/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectSW.Models;
using ProjectSW.Data;

namespace ProjectSW.Controllers
{
    /// <summary>Controlador Users, onde são executadas as ações relacionadas com os utilizadores</summary>
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        /// <summary>Construtor que guarda o contexto da build</summary>
        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>Ação que resulta na pagina com a lista de todos os utilizadores</summary>
        public IActionResult UserList()
        {
            return View(_context.User.ToList());
        }

        /// <summary>Ação que resulta no prompt para aceitar apagar o utilizador</summary>
        [Authorize(Roles = "Administrador")]
        public IActionResult DeleteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = _context.Users.FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        /// <summary>Ação que resulta no apagar o utilizador</summary>
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(UserList));
        }
    }
}

ESW02-G02/ProjectSW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Quinta do Mião </title>
    <link rel="icon" type="png" href="~/images/icon.png" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Production">
        <link rel="stylesheet" href='@Url.Content("~/lib/bootstrap/dist/css/bootstrap.css")'>
        <link rel="stylesheet" href='@Url.Content("~/css/site.css")'>
        <script src="~/js/Chart.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </environment>
    <environment exclude="Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </environment>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top .text-primary">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse text-white">

                <ul class="nav navbar-nav" style="flex-direction: unset">
                    <li class="link-homepage" style="float:left"><a asp-area="" asp-controller="Home" asp-action="Index"><b>
    Quinta do Mião
    <img src="~/images/pawprint.png" />
</b></a></li>
                </ul>
                <ul class="nav navbar-nav" style="flex-direction: unset">
                <li><a asp-area="" asp-controller="Home" asp-action="ListAnimals">Animais para Adoção</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>


    <partial name="_CookieConsentPartial" />

    <div class="container body-content">

        @RenderBody()
        <footer class="footer">
            &copy;2018 Quinta do Mião - Centro Intermunicipal de Recolha de Animais Errantes Barreiro/Moita&nbsp;&nbsp; Telefone: 212068625
            <div class="social">
                <a href="https://www.facebook.com/quintamiao/"><img class="icon" src="~/images/facebook.png" alt="Facebook Logo"></a>
            </div>
        </footer>
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
    </div>

    @RenderSection("Scripts", required: false)

</body>
</html>

ESW02-G02/ProjectSW/Views/Shared/_LayoutLogged.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Quinta do Mião </title>
    <link rel="icon" type="png" href="~/images/icon.png" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Production">
        <link rel="stylesheet" href='@Url.Content("~/lib/bootstrap/dist/css/bootstrap.css")'>
        <link rel="stylesheet" href='@Url.Content("~/css/site.css")'>
        <script src="~/js/Chart.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </environment>
    <environment exclude="Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top .text-primary">
        <div class="container" style="width: 100%">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse text-white" style="margin-left: 15%;">
                <ul class="nav navbar-nav" style="flex-direction: unset">
                    <li class="link-homepage" style="float:left"><a asp-area="" asp-controller="Home" asp-action="Index"><b>Quinta do Mião <img src="~/images/pawprint.png" /></b></a></li>
                </ul>
                <ul class="nav navbar-nav" style="flex-direction: unset; font-size:1em">
                    <li><a asp-area="" asp-controller="Animals" asp-action="Index">Animais</a></li>
                    <li><a asp-area="" asp-controller="ExitForm" asp-action="Index">Adoções</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Statistics">Estatisticas</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="UserList">Contas</a></li>
                    <li><a asp-area="" asp-controller="Employees" asp-action="Index">Funcionários</a></li>
                    <li><a asp-area="" asp-controller="Jobs" asp-action="Index">Tarefas</a></li>
                </ul>
                <partial name="_LoginPartial" />


            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    <div class="container body-content">

        @RenderBody()
        <footer class="footer">
            &copy;2018 Quinta do Mião - Centro Intermunicipal de Recolha de Animais Errantes Barreiro/Moita&nbsp;&nbsp; Telefone: 212068625
            <div class="social">
                <a href="https://www.facebook.com/quintamiao/"><img class="icon" src="~/images/facebook.png" alt="Facebook Logo"></a>
            </div>
        </footer>
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>