ESW02-G02/ProjectSW/Models/Animal.cs
using ProjectSW.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectSW.Models
{
    public class Animal
    {
        private readonly DateTime _minValue = DateTime.UtcNow.AddYears(-20);
        private readonly DateTime _maxValue = DateTime.UtcNow.AddYears(0);

        public string Id { get; set; }

        [Display(Name = "Raça")]
        public int BreedId { get; set; }

        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Display(Name = "Tamanho")]
        public string Size { get; set; }

        [Display(Name = "Genero")]
        public string Gender { get; set; }

        [DataType(DataType.Date)]
        [ValidateYearsAnimal]
        [Display(Name = "Data de nascimento")]
        public DateTime DateOfBirth { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de entrada")]
        public DateTime EntryDate { get; set; }

        [Display(Name = "Disponivel para adoção")]
        public bool Available { get; set; }

        [Display(Name = "Foto")]
        public byte[] Foto { get; set; }

        [Display(Name = "Raça")]
        public Breed Breed { get; set; }

        [Display(Name = "Anexos")]
        public List<Attachment> Attachments { get; set; }
    }
}

ESW02-G02/ProjectSW/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;

namespace ProjectSW.Controllers
{
    public class AnimalController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnimalController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Animal
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Animal/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(a => a.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animal/Create
        public IActionResult Create()
        {
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Id");
            return View();
        }

        // POST: Animal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Size,Gender,BreedId,EntryDate,Foto,FileName,Attachment")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Id", animal.BreedId);
            return View(animal);
        }

        // GET: Animal/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal.FindAsync(id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Id", animal.BreedId);
            return View(animal);
        }

        // POST: Animal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Size,Gender,BreedId,EntryDate,Foto,FileName,Attachment")] Animal animal)
        {
            if (id != animal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Id", animal.BreedId);
            return View(animal);
        }

        // GET: Animal/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(a => a.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var animal = await _context.Animal.FindAsync(id);
            _context.Animal.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(string id)
        {
            return _context.Animal.Any(e => e.Id == id);
        }
    }
}

ESW02-G02/ProjectSW/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;

namespace ProjectSW.Controllers
{
    [Authorize]
    public class AnimalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnimalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Animals
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Animals/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(a => a.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            animal.Attachments = _context.Attachment.Where(att => att.AnimalId == animal.Id).ToList();
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animals/Create
        [Authorize(Roles = "Administrador, Funcionario")]
        public IActionResult Create()
        {
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Name");
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Size,Gender,BreedId,DateOfBirth,EntryDate,Foto,Available")] Animal animal, IFormFile foto)
        {
            if (ModelState.IsValid)
            {
                var filePath = Path.GetTempFileName();

                if (foto != null && foto.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await foto.CopyToAsync(stream);
                    }
                }

                if (foto != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await foto.CopyToAsync(memoryStream);
                        animal.Foto = memoryStream.ToArray();
                    }
                }
                animal.Available = true;

                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Name", animal.BreedId);
            return View(animal);
        }

        // GET: Animals/Edit/5
        [Authorize(Roles = "Administrador, Funcionario")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal.FindAsync(id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Name", animal.BreedId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Size,Gender,BreedId,EntryDate,DateOfBirth,Foto")] Animal animal, IFormFile foto, IFormFile attachment)
        {
            if (id != animal.Id)
            {
                return NotFound();
            }

            if (animal.Attachments == null)
            {
                animal.Attachments = new List<Attachment>();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var filePath = Path.GetTempFileName();

                    if (foto != null)
                    {
                        if (foto.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await foto.CopyToAsync(stream);
                            }
                        }
                        using (var memoryStream = new MemoryStream())
                        {
                            await foto.CopyToAsync(memoryStream);
                            animal.Foto = memoryStream.ToArray();
                        }
                    }
                    else
                    {
                        animal.Foto = _context.Animal.Select(a => a.Foto).ToList().First();
                    }
                    if (attachment != null)
                    {
                        var att = new Attachment { Name = attachment.FileName };
                        if (attachment.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await attachment.CopyToAsync(stream);
                            }
                        }
                        using (var memoryStream = new MemoryStream())
                        {
                            await attachment.CopyToAsync(memoryStream);
                            att.File = memoryStream.ToArray();
                            //verificar possibilidade de juntar varios pdfs num só e guardar só esse
                            var list = new List<Attachment>
                        {
                            att
                        };
                            _context.Add(att);
                            animal.Attachments = list;
                        }
                    }
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.Set<Breed>(), "Id", "Id", animal.BreedId);
            return View(animal);
        }

        // GET: Animals/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(a => a.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var animal = await _context.Animal.FindAsync(id);
            var attachment = _context.Attachment.Select(att => att).Where(att => att.AnimalId == id).ToList();
            if (attachment != null)
                foreach (var att in attachment)
                {
                    _context.Attachment.Remove(att);
                }
            _context.Animal.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(string id)
        {
            return _context.Animal.Any(e => e.Id == id);
        }

        // eliminar attachment
        [HttpPost, ActionName("Delete-Attachment")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAttachment(string id)
        {
            var attachment = _context.Attachment.Select(att => att).Where(att => att.AnimalId == id).First();
            if (attachment != null)
                _context.Attachment.Remove(attachment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> OrderByData()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);
            var listaDeCarros = await applicationDbContext.OrderBy(c => c.EntryDate).ToListAsync();
            return View("Index", listaDeCarros);
        }

        public async Task<IActionResult> OrderByNome()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);
            return View("Index", await applicationDbContext.OrderBy(c => c.Name).ToListAsync());
        }

        public async Task<IActionResult> OrderByRaca()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);
            return View("Index", await applicationDbContext.OrderBy(c => c.Breed.Name).ToListAsync());
        }

        public async Task<IActionResult> OrderByGenero()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed);

ESW02-G02/ProjectSW/Views/Animals/Create.cshtml
@model ProjectSW.Models.Animal


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

    $(function () {
        $('[data-toggle="popover"]').popover({
            container: 'body'
        })
    })

    $('.popover-dismiss').popover({
        trigger: 'focus'
    })
</script>


<div class="div-content">
    <h2 style="font-size: 30px;"><b>Criar Ficha de Animal</b></h2>
    <hr />
    <div>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create" class="form-create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Nome" data-content="Aqui irá inserir o nome do animal.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Size" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Tamanho" data-content="Aqui irá inserir o tamanho do animal.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <select asp-for="Size" class="form-control custom-select" id="Registar-user-type">
                            <option value="Pequeno">Pequeno</option>
                            <option value="Medio">Medio</option>
                            <option value="Grande">Grande</option>
                        </select>
                        <span asp-validation-for="Size" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Data" data-content="Aqui irá inserir a data de criação da ficha.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <input asp-for="DateOfBirth" class="form-control"/>
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Género" data-content="Aqui irá inserir o género do animal.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <select asp-for="Gender" class="form-control custom-select" id="Registar-user-type">
                            <option value="Masculino">Masculino</option>
                            <option value="Feminino">Feminino</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BreedId" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Raça" data-content="Aqui irá inserir a raça do animal.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <select asp-for="BreedId" class="form-control" asp-items="ViewBag.BreedId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="EntryDate" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Data" data-content="Aqui irá inserir a data de criação da ficha.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <input asp-for="EntryDate" class="form-control" />
                        <span asp-validation-for="EntryDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Foto" class="control-label"></label>
                        <button style="background-color:#164C48; width:3em; float:right;" type="button" class="btn btn-outline-info form-control" data-toggle="popover" data-trigger="focus" title="Foto" data-content="Aqui irá inserir uma foto do animal.">
                            <img style=" width:100%" src="~/images/info_popup.png" alt="info">
                        </button>
                        <input asp-for="Foto" class="form-control" type="file" name="foto" id="foto" onchange="loadFile(event)" />
                        <span asp-validation-for="Foto" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Criar" class="button-format" style="margin-left:0%" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index"><button class="button-format" style="margin-left:31.5%"><span>Voltar</span></button></a>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ESW02-G02/ProjectSW/Views/Animals/Delete.cshtml
@model ProjectSW.Models.Animal


@{
    ViewData["Title"] = "Details";

    string imgBase64 = null;
    string imgSrc = null;
    //string fileSrc = null;
    if (Model.Foto != null)
    {
        imgBase64 = Convert.ToBase64String(Model.Foto);
        imgSrc = String.Format("data:image/gif;base64,{0}", imgBase64);
    }
    //if (Model.Attachments != null)
    //{
    //    fileSrc = String.Format("data:application/pdf;base64,{0}", Convert.ToBase64String(Model.Attachments));
    //}
}

<div class="div-content-form">
    <h2 style="font-size: 30px; margin-left:32%;"> <img src="~/images/pawprint-white.png" style="margin-right: 10%;margin-bottom: 2%;" /><b>Eliminar</b></h2>

    <div style="margin-left: 22%; margin-top: 5%; margin-bottom: 5%;">
        <h3>Tem a certeza que pretende eliminar esta ficha de Animal?</h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Size)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Size)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Breed)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Breed.Id)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EntryDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EntryDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Foto)
            </dt>
            <dd>
                <img src="@imgSrc" height="200px" width="200px" alt="Sem foto disponivel" />
            </dd>
        </dl>
        <form asp-action="Delete" style="margin-left:1%;">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Eliminar" class="delete-btn" />
            <div class="return-link"><a asp-action="Index" style="color:#164C48; text-decoration:none;">Voltar</a></div>
        </form>
    </div>

</div>

ESW02-G02/ProjectSW/Views/Animals/Index.cshtml
@model IEnumerable<ProjectSW.Models.Animal>

@{
    ViewData["Title"] = "Animais";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

<div class="div-content">
    <h2 style="font-size: 30px;"><b>Lista de Animais</b></h2>
        <form asp-controller="Animals" asp-action="Listar" class="form-create" method="post" style="width:100%; padding-left:2%; margin-left:0%">
            <label style="color:white; display:inline;">Nome:</label> <input type="text" name="filtroNome" class="form-control" style="width:15%; display:inline;">
            <label style="color:white; display:inline;">Raça:</label> <input type="text" name="filtroRaca" class="form-control" style="width:15%; display:inline;">
            <label style="color:white; display:inline;">Genero:</label> <input type="text" name="filtroGenero" class="form-control" style="width:15%; display:inline;" >
            <label style="color:white; display:inline;">Tamanho:</label> <input type="text" name="filtroTamanho" class="form-control" style="width:15%; display:inline;">
            <input style="float: right; width:15%; display:inline;" type="submit" value="Filtrar" class="button-format" />
        </form>
        <hr>
        <a asp-action="Create" class="title-link" style="font-size: 20px;"><button class="button-format"><span>Criar Nova Ficha</span></button></a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-action="OrderByNome">
                        @Html.DisplayNameFor(model => model.Name)
                    </a>
                </th>
                <th>
                    <a asp-action="OrderByRaca">
                        @Html.DisplayNameFor(model => model.Breed)
                    </a>
                </th>
                <th>
                    <a asp-action="OrderByGenero">
                        @Html.DisplayNameFor(model => model.Gender)
                    </a>
                </th>
                <th>
                    <a asp-action="OrderByTamanho">
                        @Html.DisplayNameFor(model => model.Size)
                    </a>
                </th>
                <th>
                    <a asp-action="Index">
                        @Html.DisplayNameFor(model => model.Foto)
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                string base64 = null;
                string imgSrc = null;
                if (item.Foto != null)
                {
                    base64 = Convert.ToBase64String(item.Foto);
                    imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Breed.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Size)
                    </td>
                    <td>
                        <img src="@imgSrc" height="100px" width="100px" alt="Sem foto disponivel" />
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="edit-link">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id" class="details-link">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" class="delete-link">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    /* Toggle between adding and removing the "active" class,
    to highlight the button that controls the panel */
    this.classList.toggle("active");

    /* Toggle between hiding and showing the active panel */
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
   });
  } 
    </script>