ESW02-G02/ProjectSW/Controllers/ExitFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace ProjectSW.Controllers
{
    [Authorize]
    public class ExitFormController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExitFormController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ExitForm
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ExitForm.Include(e => e.Animal);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ExitForm/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exitForm = await _context.ExitForm
                .Include(e => e.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exitForm == null)
            {
                return NotFound();
            }

            return View(exitForm);
        }

        // GET: ExitForm/Create
        [AllowAnonymous]
        public async Task<IActionResult> Create(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var animal = await _context.Animal.Include(e => e.Breed).FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["Animal"] = animal;
            ViewData["BreedName"] = animal.Breed.Name;

            return View();
        }

        // POST: ExitForm/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create([Bind("Id,AnimalId,ReportId,AdopterName,AdopterAddress,AdopterEmail,Description,Date,Motive,State")] ExitForm exitForm)
        {
            if (ModelState.IsValid)
            {
                exitForm.State = "Pendente";
                _context.Add(exitForm);
                await _context.SaveChangesAsync();

                var admins = _context.User.Where(u => u.UserType.Equals("Administrador"));

                var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
                //Antes de fazer push remover chave
                var client = new SendGridClient(apiKey);
                var msg1 = new SendGridMessage()
                {
                    From = new EmailAddress("QuintaDoMiao@exemplo.com", "Quinta do Miao"),
                    PlainTextContent = "Novo pedido de adoção",
                    Subject = "Novo pedido de adoção",
                    HtmlContent = $"Olá.<br><br>Um pedido de adoção foi efetuado, por favor verifique a lista de pedidos e dê uma resposta.<br><br>" +
                    "Cumprimentos,<br>Quinta do Mião."
                };
                foreach (ProjectSWUser admin in admins)
                {
                    msg1.AddTo(new EmailAddress(admin.Email, admin.Name));
                }
                var response1 = await client.SendEmailAsync(msg1);

                var msg2 = new SendGridMessage()
                {
                    From = new EmailAddress("QuintaDoMiao@exemplo.com", "Quinta do Miao"),
                    PlainTextContent = "Pedido de adoção",
                    Subject = "Pedido de adoção",
                    HtmlContent = $"Olá {exitForm.AdopterName}.<br>O seu pedido de adoção foi efetuado, dentro de uma semana irá receber um e-mail acerca do estado do seu pedido.<br><br>" +
                    "Cumprimentos,<br>Quinta do Mião."
                };
                msg2.AddTo(new EmailAddress(exitForm.AdopterEmail, exitForm.AdopterName));
                var response2 = await client.SendEmailAsync(msg2);

                return RedirectToAction("ExitFormSubmited", "Home");
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", "Name", exitForm.AnimalId);
            return View(exitForm);
        }

        // GET: ExitForm/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var exitForm = await _context.ExitForm
                .Include(e => e.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exitForm == null)
            {
                return NotFound();
            }
            return View(exitForm);
        }

        // POST: ExitForm/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AnimalId,AdopterName,AdopterAddress,AdopterEmail,Description,Date,Motive,State")] ExitForm exitForm)
        {
            if (id != exitForm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (exitForm.AnimalId == null)
                    {
                        return NotFound();
                    }
                    var animal = await _context.Animal.Include(e => e.Breed).FirstOrDefaultAsync(m => m.Id == exitForm.AnimalId);
                    if (animal == null)
                    {
                        return NotFound();
                    }

                    if(exitForm.State == "Granted" || exitForm.State == "Denied")
                    {
                        _context.AdoptionsHist.Add(new AdoptionsHist
                        {
                            AdopterEmail = exitForm.AdopterEmail,
                            AdopterAddress = exitForm.Description,
                            Motive = exitForm.Motive,
                            AnimalBreedName = animal.Breed.Name,
                            AnimalDateOfBirth = animal.DateOfBirth,
                            AnimalGender = animal.Gender,
                            EntryDate = animal.EntryDate,
                            Result = exitForm.State
                        });
                    }
                    if (exitForm.State == "Granted")
                    {
                        animal.Available = false;
                    }
                    _context.Update(animal);
                    _context.Update(exitForm);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExitFormExists(exitForm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", "Name", exitForm.AnimalId);
            return View(exitForm);
        }

        // GET: ExitForm/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exitForm = await _context.ExitForm
                .Include(e => e.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exitForm == null)
            {
                return NotFound();
            }

            return View(exitForm);
        }

        // POST: ExitForm/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var exitForm = await _context.ExitForm.FindAsync(id);
            _context.ExitForm.Remove(exitForm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExitFormExists(string id)
        {
            return _context.ExitForm.Any(e => e.Id == id);
        }
    }
}

ESW02-G02/ProjectSW/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjectSW.Data;
using ProjectSW.Models;
using static System.Net.WebRequestMethods;

namespace ProjectSW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>Ação que resulta na pagina principal do site</summary>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>Ação que resulta numa submissão de um exitForm para adotar um animal</summary>
        public IActionResult ExitFormSubmited()
        {
            return View();
        }

        [Authorize]
        /// <summary>Ação que resulta na pagina com as estatisticas de adoção</summary>
        public IActionResult Statistics()
        {
            return View();
        }

        /// <summary>Ação que resulta numa pagina com os detalhes de um animal</summary>
        public async Task<IActionResult> DetailsAnimal(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(a => a.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            animal.Attachments = _context.Attachment.Where(att => att.AnimalId == animal.Id).ToList();
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        /// <summary>Ação que resulta numa pagina com uma lista de animais</summary>
        public async Task<IActionResult> ListAnimals()
        {
            var applicationDbContext = _context.Animal.Include(a => a.Breed).Where(a => a.Available);
            return View(await applicationDbContext.ToListAsync());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ESW02-G02/ProjectSW/Views/Home/Components/HeatMap/HeatMapViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjectSW.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using static System.Net.WebRequestMethods;

namespace ProjectSW.Models
{
    [ViewComponent(Name = "HeatMap")]
    public class HeatMapViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;


        public HeatMapViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>Ação que resulta numa viewComponent com um heatmap com todas as localizações dos adotantes</summary>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Location> locations = new List<Location>();

            foreach (Adopter a in await _context.Adopter.ToListAsync())
            {

                locations.Add(GetLocationRequest(a.PostalCode));
            }

            return View(locations);
        }
        /// <summary>Metodo que efetua um pedido http a uma api para obter a lat e lng dado um codigo postal</summary>
        private Location GetLocationRequest(string postalcode)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create("http://api.geonames.org/postalCodeLookupJSON?postalcode=" + postalcode + "&country=PT&username=tesing_software");
            request.Method = Http.Get;

            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                if (response.StatusCode != HttpStatusCode.OK)
                {
                    throw new ApplicationException("Error: Response status " + response.StatusCode);
                }

                using (Stream responseStream = response.GetResponseStream())
                {
                    if (responseStream != null)
                    {
                        using (StreamReader reader = new StreamReader(responseStream))
                        {
                            var locations = JsonConvert.DeserializeObject<dynamic>(reader.ReadToEnd());
                            Location location = new Location { Lat = locations.postalcodes[0].lat, Lng = locations.postalcodes[0].lng };
                            return location;
                        }
                    }//end of reader
                }//End of stream
            }//End of response

            return null;
        }
    }
}

ESW02-G02/ProjectSW/Views/Home/Components/MostAdopted/MostAdoptedViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectSW.Data;
using ProjectSW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectSW.Views.Home.Components.MostAdopted
{
    [ViewComponent(Name = "MostAdopted")]
    public class MostAdoptedViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;


        public MostAdoptedViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>Ação que resulta numa viewComponent com um grafico com a idade dos animais mais adotados</summary>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Animal> animals = new List<Animal>();
            var applicationDbContext = _context.Animal;

            foreach (Animal a in await applicationDbContext.ToListAsync())
            {
                if (!a.Available)
                {
                    animals.Add(a);
                }
            }

            return View(animals);
        }
    }
}

ESW02-G02/ProjectSW/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="div-about">
                <div >
                    <h2 style="text-align: left;">
                        <img src="~/images/pawprint-white.png" /> Quem somos ...
                    </h2>
                    <br />
                    <p>
                        Situada na Quinta das Rebelas, no concelho do Barreiro (junto ao Mercado Abastecedor), a Quinta do Mião – Centro de Recolha de Animais Errantes do Barreiro e da Moita é uma obra assumida pelos municípios da Moita e Barreiro que colaboraram, assim, na criação de instalações mais modernas e adequadas do que as existentes até agora nos dois concelhos, repartindo as despesas de construção do novo equipamento e partilhando recursos.
                    </p>
                    <p>
                        A “Quinta do Mião” tem 33 boxes para cães, celas de quarentena, um gatil, um espaço administrativo, gabinete de veterinário, sala de tosquias e tratamentos e, neste seu primeiro dia de abertura, contou já com a visita de duas turmas do Ensino Pré- Escolar (uma de cada concelho).
                    </p>
                </div>
            
  
</div>

ESW02-G02/ProjectSW/Views/Home/DetailsAnimal.cshtml
@model ProjectSW.Models.Animal

@{
    ViewData["Title"] = "Details";

    string imgBase64 = null;
    string imgSrc = null;
    //string fileSrc = null;
    if (Model.Foto != null)
    {
        imgBase64 = Convert.ToBase64String(Model.Foto);
        imgSrc = String.Format("data:image/gif;base64,{0}", imgBase64);
    }
    //if (Model.Attachments != null)
    //{
    //    fileSrc = String.Format("data:application/pdf;base64,{0}", Convert.ToBase64String(Model.Attachments));
    //}
}
<div class="div-content-form">
    <h2 style="font-size: 30px; margin-left:32%;">
        <img src="~/images/pawprint-white.png" style="margin-right: 10%;margin-bottom: 2%;" /><b>Detalhes</b>
    </h2>
    <div style="margin-right: 20%; margin-left: 3%;">
        <div>
            <img src="@imgSrc" style="float:left; border-radius: 100%;" height="200px" width="200px" alt="Sem foto disponivel" />
        </div>
        <div style="margin-left: 25%; margin-top: 5%; margin-bottom: 5%; float:right;">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Size)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Size)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Gender)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Gender)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Breed)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Breed.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EntryDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Attachments)
                </dt>
                <dd>
                    @if (Model.Attachments == null)
                    {
                        <p>Sem anexos</p>
                    }
                    else
                    {
                        @foreach (var file in Model.Attachments)
                        {
                            <form asp-action="Delete-Attachment">
                                <input type="hidden" asp-for="Id" />
                                <button value="Download"><a href="@String.Format("data:application/pdf;base64,{0}", Convert.ToBase64String(file.File))" download>Download @file.Name</a></button>
                                <input type="submit" value="Delete" class="btn btn-default" /> <br />
                            </form>
                        }
                    }

                </dd>
            </dl>
        </div>
    </div>
    <div style="margin-left:25%">
        <div class="return-link" style="margin-left: 13%; margin-top: 10%;"><a asp-action="ListAnimals" style="color:#164C48; text-decoration:none;">Voltar</a></div>
        <a asp-area="" asp-controller="ExitForm" asp-action="Create" asp-route-animalId="@Model.Id">Adotar</a>
    </div>
</div>

ESW02-G02/ProjectSW/Views/Home/ExitFormSubmited.cshtml
@{
    ViewData["Title"] = "Pedido de adoção";
}

<div class="div-content">
    <h2 style="font-size: 30px; text-align: left;"><b>@ViewData["Title"]</b></h2>
    <p>
        O seu pedido foi submetido.
    </p>
    <p>
        Receberá uma resposta via Email
    </p>
</div>

ESW02-G02/ProjectSW/Views/Home/Index.cshtml
@model IEnumerable<ProjectSW.Models.Animal>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container body-content">
    <div class="slideshow-container">

        <div class="mySlides">
            <img style="width: 60%; filter: drop-shadow(0px 0px 3px #000000);" src="~/images/quinta.jpg" />
        </div>

        <div class="mySlides">
            <img style="width: 60%; filter: drop-shadow(0px 0px 3px #000000);" src="~/images/inauguracao.jpg" />
        </div>

        <div class="mySlides">
            <h3 style="text-align: left">
                <img src="~/images/pawprint-white.png" /> Quinta do Mião
            </h3>
            <br />
            <p style="text-align: justify;">
                Situada na Quinta das Rebelas, no concelho do Barreiro (junto ao Mercado Abastecedor), a Quinta do Mião – Centro de Recolha de Animais Errantes do Barreiro e da Moita é uma obra assumida pelos municípios da Moita e Barreiro que colaboraram, assim, na criação de instalações mais modernas e adequadas do que as existentes até agora nos dois concelhos, repartindo as despesas de construção do novo equipamento e partilhando recursos.

                A “Quinta do Mião” tem 33 boxes para cães, celas de quarentena, um gatil, um espaço administrativo, gabinete de veterinário, sala de tosquias e tratamentos e, neste seu primeiro dia de abertura, contou já com a visita de duas turmas do Ensino Pré- Escolar (uma de cada concelho).
            </p>
        </div>

        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>

    </div>

    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
    </script>
</div>

ESW02-G02/ProjectSW/Views/Home/ListAnimals.cshtml
@model IEnumerable<ProjectSW.Models.Animal>
@{
    ViewData["Title"] = "Animais";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="div-content" style="background-color: white; border-radius: 4px; padding: 5px; width: 90%;">
    <h2 style="font-size: 30px;  margin-bottom: 50px; color:#164C48;"><b>Lista de Animais</b></h2>



    @foreach (var item in Model)
    {
        string base64 = null;
        string imgSrc = null;
        string nome = item.Name;

        var year = @DateTime.Now.Year - @item.DateOfBirth.Date.Year;

        

        if (item.Foto != null)
        {
            base64 = Convert.ToBase64String(item.Foto);
            imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        }



        <div class="container-img">
            <div class="hovereffect">
                <img class="img-animal" src="@imgSrc" height="200px" width="200px" alt="Sem foto disponivel" />
                <div class="overlay">
                    <button onclick="showModal(@item.Name);" style="background: transparent; border: none; margin-right: 15px;  margin-top: 20px; outline:0;">
                        <p class="info">@nome</p>
                    </button>
                </div>
            </div>
        </div>

        <div id="@item.Name" class="modal">
            <div class="modal-content" style="text-align:center; font-size:24px;">
                <div class="modal-header">
                    <span class="close @item.Id">&times;</span>
                    <p class="info-animal"><b>@item.Name</b></p>
                </div>
                <div class="modal-body" style="font-size:20px;">
                    <img class="img-animal" src="@imgSrc" style="height:200px; width:200px; float:left;" alt="Sem foto disponivel" />
                    <img src="~/images/pawprint.png" />   <p class="info-animal" style="margin-right:22%"><b>@year ano(s)</b></p><br /><br />
                    <img src="~/images/pawprint.png" />   <p class="info-animal" style="margin-right:22%"><b>@item.Breed.Name</b></p><br /><br />
                    <img src="~/images/pawprint.png" />   <p class="info-animal" style="margin-right:22%"><b>@item.Size</b></p><br /><br />
                    <img src="~/images/pawprint.png" />   <p class="info-animal" style="margin-right:22%"><b>@item.Gender</b></p><br /><br />
                </div>
                <div class="modal-footer">
                    <p style="text-align: center;"> <a asp-area="" asp-controller="ExitForm" asp-action="Create" asp-route-id="@item.Id" style="color:white;">Fazer Pedido de Adoção</a></p>
                </div>

            </div>
        </div>


        <script>
            var modal = document.getElementById("myModal @item.Id");
            var span = document.getElementsByClassName("close @item.Id")[0];

            function showModal(id) {
                modal = id;
                id.style.display = "block";
            }
            span.onclick = function () {
                modal.style.display = "none";
            }
            window.onclick = function (event) {
                if (event.target == modal) {
                    modal.style.display = "none";
                }
            }
           
        </script>



    }


</div>

ESW02-G02/ProjectSW/Views/Home/MostAdopted.cshtml
@model IEnumerable<ProjectSW.Models.Animal>
@{
    ViewData["Title"] = "MostAdoptedView";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}
<br /><br /><br />

<h2>Idades dos animais mais adotados</h2>

<div class="col-md-5">
    <canvas id="myChart" style="background-color:white;"></canvas>
</div>

<script type="text/javascript">
    function GetAnimalData() {
        var animals = @Html.Raw(Json.Serialize(Model));
        var ageData = [0, 0, 0, 0, 0];
        for (i = 0; i < animals.length; i++) {
            var age = @DateTime.Now.Year - parseInt(animals[i].dateOfBirth.substring(0, 4), 10);
            switch (age) {
                case 0:
                case 1:
                case 2:
                    ageData[0]++;
                    break;
                case 3:
                case 4:
                case 5:
                    ageData[1]++;
                    break;
                case 6:
                case 7:
                case 8:
                    ageData[2]++;
                    break;
                case 9:
                case 10:
                    ageData[3]++;
                    break;
                default:
                    ageData[4]++;
                    break;
            }
        }
        return ageData;
    }

    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["0-2", "3-5", "6-8", "9-10", "10>"],
            datasets: [{
                label: 'idade dos animais adotados',
                data: GetAnimalData(),
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

</script>

ESW02-G02/ProjectSW/Views/Home/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
}
<br><br><br><br>

<div>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#first" aria-controls="first" role="tab" data-toggle="tab">HeatMap</a>
        </li>
        <li role="presentation">
            <a href="#second" aria-controls="second" role="tab" data-toggle="tab">Grafico da idade</a>
        </li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="first" style="background-color:transparent; width:450px; height:300px; margin-top:1%">
            <h3>Heatmap com a localização dos animais adotados</h3>
            @(await Component.InvokeAsync("HeatMap"))
        </div>
        <div role="tabpanel" class="tab-pane" id="second" style="background-color:transparent;">
            <h2>Idades dos animais mais adotados</h2>
            @(await Component.InvokeAsync("MostAdopted"))
        </div>
    </div>
</div>